# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [11]:
import numpy as np

a = np.random.randint(10, size=6) 
print('a:',a)
print('list(a): ', list(a))
print('a.tolist(): ', a.tolist())

b = np.random.randint(10, size=(3,4))
print('b:',b)
print('list(b): ', list(b))
print('b.tolist(): ', b.tolist())


a: [6 4 4 2 3 4]
list(a):  [6, 4, 4, 2, 3, 4]
a.tolist():  [6, 4, 4, 2, 3, 4]
b: [[8 9 9 5]
 [0 1 1 0]
 [9 8 7 9]]
list(b):  [array([8, 9, 9, 5]), array([0, 1, 1, 0]), array([9, 8, 7, 9])]
b.tolist():  [[8, 9, 9, 5], [0, 1, 1, 0], [9, 8, 7, 9]]


In [12]:


import numpy as np

a = np.random.randint(10, size=6) 

print(a)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[6 2 4 3 1 0]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [13]:
b = np.random.randint(10, size=(3,4)) 

print(b)

print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[3 6 7 4]
 [8 2 0 0]
 [0 4 9 2]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [14]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)

print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[2 2]
  [5 5]
  [3 0]]

 [[6 2]
  [8 4]
  [2 1]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


In [15]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[9, 8, 3, 3, 6, 7]
[9, 8, 3, 3, 6, 7]


In [16]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 0, 0, 5], [9, 0, 7, 6], [2, 7, 8, 6]]
[array([5, 0, 0, 5]), array([9, 0, 7, 6]), array([2, 7, 8, 6])]


In [17]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[8, 2], [7, 6], [4, 5]], [[4, 6], [7, 9], [4, 8]]]
[array([[8, 2],
       [7, 6],
       [4, 5]]), array([[4, 6],
       [7, 9],
       [4, 8]])]


In [18]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[9, 8, 3, 3, 6, 7]
[[5, 0, 0, 5], [9, 0, 7, 6], [2, 7, 8, 6]]
[[[8, 2], [7, 6], [4, 5]], [[4, 6], [7, 9], [4, 8]]]
