[簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？


print(np.zeros((2, 3)))

print(np.empty((2, 3)))

在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。

承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

In [4]:
import numpy as np
a = np.random.rand(2, 3)


a = a * 100

print(a)
print(a.round())
print(np.round(a))

[[36.68678237 11.93203551 92.75084715]
 [ 5.50085513  5.7595     98.99911952]]
[[37. 12. 93.]
 [ 6.  6. 99.]]
[[37. 12. 93.]
 [ 6.  6. 99.]]


In [6]:
m = 20
n = 40
a = np.random.rand(2, 3) * (n - m)
b = a

print((a - b % 1) + m)

[[21. 25. 35.]
 [24. 28. 20.]]
